### ISSUE TITLE
Should Blueprint41.Neo4j.Persistence.Void.Neo4jTransaction.Run be doing something?

### ISSUE THREAD

**Issue by SidneyAks** [circles-arrows/blueprint41#17]
Looking at this library to assess it's viability for a neo4j orm. I'm having some difficulty doing the [movies example from the wiki](https://github.com/circles-arrows/blueprint41/wiki/Getting-Started). I find in my program.cs when I run `Model.Execute(true);` I get the error `Due to an unexpected state of the neo4j transaction, it seems impossible to insert the Genre at this time`

I traced this down to Blueprint41.Neo4j.Persistence.Void.Neo4jNodePersistenceProvider.Insert:171; there is a check to see if the result of a transaction is empty; but it appears that the Blueprint41.Neo4j.Persistence.Void.Neo4jTransaction.Run function [doesn't actually do anything other than construct an empty Neo4jRawResult object](https://github.com/circles-arrows/blueprint41/blob/master/Blueprint41/Neo4j/Persistence/Void/Neo4jTransaction.cs) which would always result an in empty result. Am I doing something wrong here?

**Comment by circles-arrows** [comment]
Thanks for having a look at Blueprint41 and I’m sorry to hear your ran into trouble. 

You should not have had an instance of Blueprint41.Neo4j.Persistence.**Void**.Neo4jTransaction.Run, this object exists mainly to be able to run "Model.Execute(false);" without being connected to a real database. You could use that “void connection” if you want to query the model to generate code from it or some documentation, but not to read from or write to the database.

I suspect you got a copy of the “void connection” because you are missing the setup of the neo4j driver and your database connection. Possibly it also could be you are not having this setup at the entry-point of your application before you execute the model.

Example driver and database connection setup code:
```
using Blueprint41.Core;
using neo4j = Blueprint41.Neo4j.Persistence.Driver.v4;  // Driver.v5 will be coming soon

neo4j.Neo4jPersistenceProvider driver = new neo4j.Neo4jPersistenceProvider("bolt://localhost:7687", "[USERNAME_HERE]", "[PASSWORD_HERE]");
PersistenceProvider.CurrentPersistenceProvider = driver;
```

Hope this solves your problem, and we’ll have a look at the wiki to see if we can improve this topic.

**Comment by SidneyAks** [comment]
Using the new driver instance I am able to get further, Reviewing the docs it looks like the version specific neo4j using statement and the creation of the PersistanceProvider need to be updated;

![image](https://user-images.githubusercontent.com/19693194/232975053-5c9169da-cb61-4743-b9dc-11d67597ac4a.png)

I'm having other issues but will make sure I'm correct to this point and open a new issue if I can't resolve. Thank you!
