### ISSUE TITLE
Cannot find blueprint41 procedures after upgrading to 4.0.*

### ISSUE THREAD

**Issue by hewhofreeks** [circles-arrows/blueprint41#4]
I've been working on a local database using neo4j 3.5.5 and blueprint41 for a few weeks now and decided to spin up an instance for hosting in AWS using the newer version of 4.0.4. Spent a little while trying to get it configured and eventually found that none of the procedures in the blueprint41 jar file are being loaded.  I run the following query to see all the procedures and can see all the apoc ones fine but none of the blueprint41 ones:

```
CALL dbms.procedures() YIELD name
RETURN head(split(name,".")) as package, count(*), collect(name) as procedures;
```

To test to make sure it is a difference between the versions I went and ran this query against my local graph while running 3.5.5, I did see the blueprint41 procedures in the list, then I upgraded my local version, confirmed the settings are still in place and the plugin is still available, but am still not seeing any of the blueprint41 procedures.

Is the current plugin not available with newer versions of Neo4j?

**Comment by circles-arrows** [comment]
The current plugin is not compatible with neo4j 4, furthermore the driver 1.7.2 that blueprint41 uses is also not compatible with neo4j 4. Unfortunately the new driver of neo4j only has backward compatibility for version 3.5.x and upgrading the drivers on blueprint41 would therefore force anyone with an older setup to upgrade.

Referencing the new neo4j driver v4 and upgrading the plugin to neo4j 4.x needs code rewrites. The rewrites for referencing the v4 driver are done, but the plugin not yet. Unfortunately, if we release the changes now, we are left with a situation where blueprint41 is only compatible with neo4j 3.5.x instead of the current situation where blueprint41 is compatible with all neo4j versions before 4.x

But 4.x support is coming soon

**Comment by hewhofreeks** [comment]
Thanks for the update! It's no problem for the time being. Our project isn't dependent on neo4j v4.x but I'm happy to hear that the support is coming.
