### ISSUE TITLE
Neo4J Aura

### ISSUE THREAD

**Issue by rodoflho** [circles-arrows/blueprint41#9]
Can I blueprint41 a neo4j Aura?

**Comment by circles-arrows** [comment]
We have not yet tried using it with neo4j Aura, but one thing I know will not work is the "functional id" feature. If you just not use that feature it should all work (in theory).

The plan is for 2021 Q2 we will start testing and tweaking blueprint41 on Neo4j Aura. After thats done we will officially support compatability with Neo4j Aura.

If you don't want to wait for that, you can just start using it now. If it turns out that blueprint41 does not work well for you on Neo4j Aura, I can promise that we will still address any issues you encounter with Neo4j Aura, even though it's not officially supported. Just submit a support request on https://www.blueprint41.com/ (right top corner)

**Comment by RyanFerretti** [comment]
Has there been any progress on supporting Aura? I see there was a checkin talking about it: https://github.com/circles-arrows/blueprint41/commit/ae3f2e45d06fc8d52cc9102b72bb7757b4a20aa6

We are self hosting now and has been a pain so we are trying to figure out what we want to do going forward.

**Comment by circles-arrows** [comment]
All changes needed for Blueprint41 to work with Neo4j Aura are now checked in. We're still doing testing and will make an Nuget release next week, but you can already see if it works on your side if you build from the latest source code.

One known limitation of Aura, you cannot use the Numerical or Hash Functional Ids, instead you must use:
FunctionalIds.Default = FunctionalIds.UUID;

Another thing, on Aura don't send the database name when connecting. When you do you'll get an error about the routing table.

Internally we have Blueprint41 working with Neo4j Aura and I'm confident any issues specific to Aura you might run into will be minor and easily fixed.

**Comment by RobHudson72** [comment]
Question.... Does this mean that in the modeller, we should not define FunctionalIds for each entity, but rather let FunctionalIDs.Default take care of everything?
